# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name trim_ws
#' @title trim_ws
#' @description Removes leading and trailing spaces from a string
#' @param s A single string
#' @return A string with no leading or trailing spaces
NULL

#' @name splitHeaderLines
#' @title splitHeaderLines
#' @description Splits lines from an LAS header
#' @param lines Vector of LAS header strings
#' @return A data.frame of parsed header values
#' @export
#' @useDynLib lasr
#' @importFrom Rcpp sourceCpp
splitHeaderLines <- function(lines) {
    .Call('_lasr_splitHeaderLines', PACKAGE = 'lasr', lines)
}

