# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name parse_curves
#' @title parse_curves
#' @description A function to parse delimited curve data from a LAS file.
#' @param lines A vector of strings containing log curve data
#' @param delim A string specifying the delimiter
#' @param curve_names A vector of strings containing the names of the log curves
#' @param null_val A double indicating what value to replace with NA
#' @param first_line An integer indicating the index of the first line in lines containing log data
#' @param last_line An integer indicating the last index of lines containing log data.
#' @return A dataframe containing the curves
parse_curves <- function(lines, curve_names, delim = " ", null_val = -999.25, first_line = 0L, last_line = -1L) {
    .Call('_lasr_parse_curves', PACKAGE = 'lasr', lines, curve_names, delim, null_val, first_line, last_line)
}

#' @name trim_ws
#' @title trim_ws
#' @description A function to trim the whitespace from the ends of a string
#' @param s A string
#' @return A string with no whitespace
trim_ws <- function(s) {
    .Call('_lasr_trim_ws', PACKAGE = 'lasr', s)
}

#' @name parse_header
#' @title parse_header
#' @description A function to parse header lines from a LAS file.
#' @param lines A vector of strings containing header data.
#' @param first_line An integer indicating the index of the first line in lines containing header data.
#' @param last_line An integer indicating the last index of lines containing header data.
#' @return A dataframe containing the header data.
parse_header <- function(lines, first_line = 0L, last_line = -1L) {
    .Call('_lasr_parse_header', PACKAGE = 'lasr', lines, first_line, last_line)
}

#' @name get_header_double
#' @title get_header_double
#' @description A function to get a double value from a header
#' @param header A DataFrame containing header data
#' @param mnem A string containing the desired mnemonic
#' @param default_val A double to be used if the value can't be found or converted
#' @return A double containing the value
#' @export
get_header_double <- function(header, mnem, default_val) {
    .Call('_lasr_get_header_double', PACKAGE = 'lasr', header, mnem, default_val)
}

#' @name get_header_int
#' @title get_header_int
#' @description A function to get an int value from a header
#' @param header A DataFrame containing header data
#' @param mnem A string containing the desired mnemonic
#' @param default_val An int to be used if the value can't be found or converted
#' @return An int containing the value
#' @export
get_header_int <- function(header, mnem, default_val) {
    .Call('_lasr_get_header_int', PACKAGE = 'lasr', header, mnem, default_val)
}

#' @name get_header_string
#' @title get_header_string
#' @description A function to get a string value from a header
#' @param header A DataFrame containing header data
#' @param mnem A string containing the desired mnemonic
#' @return A string containing the value
#' @export
get_header_string <- function(header, mnem) {
    .Call('_lasr_get_header_string', PACKAGE = 'lasr', header, mnem)
}

#' @useDynLib lasr
#' @importFrom Rcpp sourceCpp
#' @name read_las_cpp
#' @title read_las_cpp
#' @description A function to read LAS files.  Not really meant to be called by the user.
#' @param lines A vector of lines with blank lines and leading whitespace removed
#' @param header_only If true, will only return the header portions.
#' @return A two part list
read_las_cpp <- function(lines, header_only = FALSE) {
    .Call('_lasr_read_las_cpp', PACKAGE = 'lasr', lines, header_only)
}

